/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.beothorn.telegramAIConnector;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
